/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import controles.ControlCrearPartida;
import javax.swing.JOptionPane;

/**
 *
 * @author fermi
 */
public class FrmCrearPartida extends javax.swing.JFrame {

     private static FrmCrearPartida crearPartida;
     
    /**
     * Creates new form FrmPartida
     */
    public FrmCrearPartida() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setResizable(false);
        this.agregarActionListeners(new ControlCrearPartida(this));
    }
    
    public void inicializarComandos(){
        if (cuatroC.isSelected()) { 
            this.btnListo.setActionCommand("listo4");
        } else if (cincoC.isSelected()) {
            this.btnListo.setActionCommand("Listo5");
        } else if (seisC.isSelected()) {
            this.btnListo.setActionCommand("Listo6");
        } else if (sieteC.isSelected()) {
            this.btnListo.setActionCommand("Listo7");
        }
        
    }
    
    private void agregarActionListeners(ControlCrearPartida ctrlCrearPartida){
        this.btnListo.addActionListener(ctrlCrearPartida);
    }
    
    public static FrmCrearPartida getInstance() {
        if (crearPartida == null) {
            return crearPartida = new FrmCrearPartida();
        } else if (crearPartida != null) {
            return crearPartida;
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgCasillas = new javax.swing.ButtonGroup();
        btgJugadores = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnListo = new javax.swing.JButton();
        cuatroC = new javax.swing.JRadioButton();
        cincoC = new javax.swing.JRadioButton();
        seisC = new javax.swing.JRadioButton();
        sieteC = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dosJ = new javax.swing.JRadioButton();
        tresJ = new javax.swing.JRadioButton();
        cuatroJ = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtApuesta = new javax.swing.JTextField();
        txtFondos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(199, 213, 76));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(154, 181, 42), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(174, 35, 13));
        jLabel3.setText("crear partida");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 32, 6));
        jLabel4.setText("casillas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mm5.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 410));

        btnListo.setBackground(new java.awt.Color(155, 3, 2));
        btnListo.setFont(new java.awt.Font("Algerian", 0, 26)); // NOI18N
        btnListo.setForeground(new java.awt.Color(248, 228, 180));
        btnListo.setText("Listo");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        jPanel1.add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 170, -1));

        cuatroC.setBackground(new java.awt.Color(199, 213, 76));
        btgCasillas.add(cuatroC);
        cuatroC.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        cuatroC.setForeground(new java.awt.Color(68, 32, 6));
        cuatroC.setText("4");
        jPanel1.add(cuatroC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        cincoC.setBackground(new java.awt.Color(199, 213, 76));
        btgCasillas.add(cincoC);
        cincoC.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        cincoC.setForeground(new java.awt.Color(68, 32, 6));
        cincoC.setText("5");
        jPanel1.add(cincoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        seisC.setBackground(new java.awt.Color(199, 213, 76));
        btgCasillas.add(seisC);
        seisC.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        seisC.setForeground(new java.awt.Color(68, 32, 6));
        seisC.setText("6");
        jPanel1.add(seisC, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        sieteC.setBackground(new java.awt.Color(199, 213, 76));
        btgCasillas.add(sieteC);
        sieteC.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        sieteC.setForeground(new java.awt.Color(68, 32, 6));
        sieteC.setText("7");
        jPanel1.add(sieteC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 32, 6));
        jLabel6.setText("Num. jugadores");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 32, 6));
        jLabel7.setText("Num. fichas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(199, 213, 76));
        jComboBox1.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(68, 32, 6));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(68, 32, 6));
        jLabel8.setText("fondos de apuesta");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 32, 6));
        jLabel9.setText("valor por apuesta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        dosJ.setBackground(new java.awt.Color(199, 213, 76));
        btgJugadores.add(dosJ);
        dosJ.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        dosJ.setForeground(new java.awt.Color(68, 32, 6));
        dosJ.setText("2");
        jPanel1.add(dosJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        tresJ.setBackground(new java.awt.Color(199, 213, 76));
        btgJugadores.add(tresJ);
        tresJ.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        tresJ.setForeground(new java.awt.Color(68, 32, 6));
        tresJ.setText("3");
        jPanel1.add(tresJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        cuatroJ.setBackground(new java.awt.Color(199, 213, 76));
        btgJugadores.add(cuatroJ);
        cuatroJ.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        cuatroJ.setForeground(new java.awt.Color(68, 32, 6));
        cuatroJ.setSelected(true);
        cuatroJ.setText("4");
        jPanel1.add(cuatroJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 32, 6));
        jLabel5.setText("Tamaño del tablero");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 310, -1));

        txtApuesta.setBackground(new java.awt.Color(248, 228, 180));
        jPanel1.add(txtApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 80, 30));

        txtFondos.setBackground(new java.awt.Color(248, 228, 180));
        jPanel1.add(txtFondos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FrmPrincipal frmPrincipal = FrmPrincipal.createPrincipal();
        frmPrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCasillas;
    private javax.swing.ButtonGroup btgJugadores;
    private javax.swing.JButton btnListo;
    private javax.swing.JRadioButton cincoC;
    private javax.swing.JRadioButton cuatroC;
    private javax.swing.JRadioButton cuatroJ;
    private javax.swing.JRadioButton dosJ;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton seisC;
    private javax.swing.JRadioButton sieteC;
    private javax.swing.JRadioButton tresJ;
    private javax.swing.JTextField txtApuesta;
    private javax.swing.JTextField txtFondos;
    // End of variables declaration//GEN-END:variables
}
