/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import controles.ControlMnuPrincipal;

 
/**
 *
 * @author fermi
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private static FrmPrincipal frmPrincipal;

    /**
     * Creates new form Principal
     */
    private FrmPrincipal() {
        initComponents();
        this.setTitle("Patolli");
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
        this.inicializarComandos();
        this.agregarActionLisneters(new ControlMnuPrincipal(this));
    }

    private void inicializarComandos(){
        this.btnComoJugar.setActionCommand("Como jugar");
        this.btnCrearPartida.setActionCommand("CrearPartida");
        this.btnIngresarPartida.setActionCommand("Ingresar partida");
        this.btnSalir.setActionCommand("salir");
    }
    
    private void agregarActionLisneters(ControlMnuPrincipal ctrlPrincipal){
        this.btnComoJugar.addActionListener(ctrlPrincipal);
        this.btnCrearPartida.addActionListener(ctrlPrincipal);
        this.btnIngresarPartida.addActionListener(ctrlPrincipal);
        this.btnSalir.addActionListener(ctrlPrincipal);
    }
    /**
     * Contructor que crea el frame principal
     * @return regresa una instancia de frame principal, aplicando singleton
     */
    public static FrmPrincipal createPrincipal() {
        if (frmPrincipal == null) {
            return frmPrincipal = new FrmPrincipal();
        } else if (frmPrincipal != null) {
            return frmPrincipal;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIngresarPartida = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCrearPartida = new javax.swing.JButton();
        btnComoJugar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 56, 12), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarPartida.setBackground(new java.awt.Color(155, 56, 12));
        btnIngresarPartida.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        btnIngresarPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarPartida.setText("ingresar a partida");
        jPanel1.add(btnIngresarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 180, 40));

        btnSalir.setBackground(new java.awt.Color(155, 56, 12));
        btnSalir.setFont(new java.awt.Font("Algerian", 0, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 180, 40));

        btnCrearPartida.setBackground(new java.awt.Color(155, 56, 12));
        btnCrearPartida.setFont(new java.awt.Font("Algerian", 0, 16)); // NOI18N
        btnCrearPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPartida.setText("Crear partida");
        jPanel1.add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, 40));

        btnComoJugar.setBackground(new java.awt.Color(155, 56, 12));
        btnComoJugar.setFont(new java.awt.Font("Algerian", 0, 16)); // NOI18N
        btnComoJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnComoJugar.setText("Como jugar");
        jPanel1.add(btnComoJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 180, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/maya2.PNG"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(196, 72, 17));
        jLabel2.setText("PATOLLI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FrmPrincipal frm = FrmPrincipal.createPrincipal();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComoJugar;
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnIngresarPartida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
