/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import controles.ControlngresarPartida;
import entidades.Jugador;
import java.awt.Color;
import java.util.Observable;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import modelos.ModeloIngresarPartida;

/**
 *
 * @author fermi
 */
public class FrmIngresarPartida extends javax.swing.JFrame implements FrameBase<ControlngresarPartida, ModeloIngresarPartida> {

    private Color color;
    /**
     * Creates new form FrmIngresar
     */
    private static FrmIngresarPartida frmIngresaP;
    private ControlngresarPartida ctrlIngresarPartida;

    private FrmIngresarPartida() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.ctrlIngresarPartida= ControlngresarPartida.getInstance();
        this.setResizable(false);
        this.setVisible(false);
        this.color = null;
    }

    public static FrmIngresarPartida getInstance() {
        if (frmIngresaP == null) {
            return frmIngresaP = new FrmIngresarPartida();
        } else if (frmIngresaP != null) {
            return frmIngresaP;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnColor = new javax.swing.JButton();
        checkColor = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(69, 38, 29));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 38, 29), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 207, 127));
        jLabel3.setText("Ingresar a partida");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(131, 151, 8));
        jLabel4.setText("Nombre de usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mm1.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(250, 203, 139));
        txtNombre.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 240, 40));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(131, 151, 8));
        jLabel5.setText("Color");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(177, 6, 7));
        jButton1.setFont(new java.awt.Font("Algerian", 0, 26)); // NOI18N
        jButton1.setForeground(new java.awt.Color(247, 180, 93));
        jButton1.setText("Listo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 170, -1));

        btnColor.setText("Selecciona el color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 240, 30));

        checkColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkColorActionPerformed(evt);
            }
        });
        jPanel1.add(checkColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FrmPrincipal frmPrincipal = FrmPrincipal.getInstance();
        frmPrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void checkColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkColorActionPerformed

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        if(seleccionaColor()){
            System.out.println("El color es"+this.color.toString());
        }else{
            JOptionPane.showMessageDialog(this, "");
        }
    }//GEN-LAST:event_btnColorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private boolean validarCampos(){
        return true;
    }
    
    private boolean seleccionaColor(){
        //Ver que pasa un vez que ya has seleciona una vez
        color = JColorChooser.showDialog(this, "Selecione un color", color);
        if(color==null){
            return false;
        }else{
            return true;
        }
    }
    
    private void ingresarPartida(){
        this.ctrlIngresarPartida.ingresarPartida(this.crearInstanciaJugador());
    }
    
    private Jugador crearInstanciaJugador(){
        Jugador j = new Jugador(this.txtNombre.getText(), color.toString());
        return j;
    }
    
    @Override
    public void asignarEtiquetas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void asignarComando() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void asignarEventos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void update(Observable arg0, Object arg1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.JCheckBox checkColor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
