/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import controles.ControlBase;
import controles.ControlTablero;
import dibujos.Fachada;
import dibujos.IDibujoTablero;
import java.util.Observable;
import modelos.ModeloTablero;

/**
 *
 * @author fermi
 */
public class FrmTablero extends javax.swing.JFrame implements FrameBase<ControlTablero, ModeloTablero> {

    private IDibujoTablero dibujadorTablero;
    private ModeloTablero modeloTablero;
    private int i=0;
    private static FrmTablero frmTablero;
    
    private FrmTablero() {
        initComponents();
        this.modeloTablero= ModeloTablero.getInstance();
        this.modeloTablero.addObserver(this);
        this.dibujadorTablero= new Fachada(modeloTablero.getTablero());
        this.setLocationRelativeTo(null);
        this.setTitle("Tablero");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
        this.agregarElementoPantalla();
        this.asignarEtiquetas();
    }
    
    public static FrmTablero getInstance(){
        if (frmTablero==null) {
            return frmTablero= new FrmTablero();
        }
        return frmTablero;
    }
    
    public void agregarElementoPantalla(){
        this.dibujadorTablero.dibujarTablero();
        this.agregarInfoJugadores();
    }
                
    public void agregarInfoJugadores(){
//        
//        for(Jugador jugador: modeloTablero.getJugadores()){
//            
//        }
    } 
    
//    private JPanel obtenerPanel(){
//        switch(i){
//            case 0:
//                return this.jPanel1;
//                break;
//            case 1:
//                break;
//            case 2:
//                break;
//            case 3:
//                break;
//        }
//        return null;
//    }
    private void agregarFicha() {
//        canvas.agregarFichas(new Ficha(1),1);
//        canvas.agregarFichas(new Ficha(2),2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jugador4 = new javax.swing.JLabel();
        jugador1 = new javax.swing.JLabel();
        jugador3 = new javax.swing.JLabel();
        jugador2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        JPJugador1 = new javax.swing.JPanel();
        JPJugador3 = new javax.swing.JPanel();
        JPJugador2 = new javax.swing.JPanel();
        JPJugador4 = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 56, 12), 3));

        jugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m1.PNG"))); // NOI18N

        jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m4.PNG"))); // NOI18N

        jugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m3.PNG"))); // NOI18N

        jugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m2.PNG"))); // NOI18N

        jButton2.setText("Tirar Fichas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPJugador1Layout = new javax.swing.GroupLayout(JPJugador1);
        JPJugador1.setLayout(JPJugador1Layout);
        JPJugador1Layout.setHorizontalGroup(
            JPJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        JPJugador1Layout.setVerticalGroup(
            JPJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPJugador3Layout = new javax.swing.GroupLayout(JPJugador3);
        JPJugador3.setLayout(JPJugador3Layout);
        JPJugador3Layout.setHorizontalGroup(
            JPJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPJugador3Layout.setVerticalGroup(
            JPJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPJugador2.setPreferredSize(new java.awt.Dimension(110, 100));

        javax.swing.GroupLayout JPJugador2Layout = new javax.swing.GroupLayout(JPJugador2);
        JPJugador2.setLayout(JPJugador2Layout);
        JPJugador2Layout.setHorizontalGroup(
            JPJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        JPJugador2Layout.setVerticalGroup(
            JPJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPJugador4.setPreferredSize(new java.awt.Dimension(110, 100));

        javax.swing.GroupLayout JPJugador4Layout = new javax.swing.GroupLayout(JPJugador4);
        JPJugador4.setLayout(JPJugador4Layout);
        JPJugador4Layout.setHorizontalGroup(
            JPJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        JPJugador4Layout.setVerticalGroup(
            JPJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblTittle.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(255, 207, 127));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador3)
                    .addComponent(jugador2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPJugador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblTittle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JPJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jugador1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JPJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugador4)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jugador4)
                        .addComponent(jugador3))
                    .addComponent(JPJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JPJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jugador2)
                                .addComponent(JPJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JPJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jugador1)
                                .addGap(4, 4, 4)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(53, 53, 53))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FrmPrincipal frmPrincipal = FrmPrincipal.getInstance();
        frmPrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.tirarCanias();
     }//GEN-LAST:event_jButton2ActionPerformed
    private void tirarCanias(){
        //agregar metodo para tirar cania Logica
        //Ctrl
    }
    
    private void agregarJugadores(){
        
    }
    
    /**
     * Crear metodo en el control para avisar a los demás jugadores
     * cuidar que los metodos que modifiquen el modelo pasen por el control y directo al modelo, para respetar el estilo.
     */
//    public List<Cania> tirarCanias() {
//        Random rd = new Random();
//        for (int i = 0; i < 5; i++) {
//            Boolean b= rd.nextBoolean();            
//            this.modeloTablero.canias.add(new Cania(b));
//        }
//        System.out.println(this.modeloTablero.canias);
//        return canias;
//    }UnsupportedOperationException
//
//    public Integer contarCanias() {
//        List<Cania> turno = tirarCanias();
//        Integer contador = 0;
//        for (Cania b : turno) {
//            if (b.getValor() == true) {
//                contador++;
//            }
//        }
//        return contador;
//    }

//    public Integer resultadoTurno() {
//        Integer numCanias = contarCanias();
//        if (numCanias == 5) {
//            return 10;
//        } else {
//            return numCanias;
//        }
////    }

    @Override
    public void asignarEtiquetas() {
        this.lblTittle.setText(this.modeloTablero.getEtiqueta(0));
    }

    @Override
    public void asignarComando() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void asignarEventos(ControlBase control) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void update(Observable arg0, Object arg1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPJugador1;
    private javax.swing.JPanel JPJugador2;
    private javax.swing.JPanel JPJugador3;
    private javax.swing.JPanel JPJugador4;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jugador1;
    private javax.swing.JLabel jugador2;
    private javax.swing.JLabel jugador3;
    private javax.swing.JLabel jugador4;
    private javax.swing.JLabel lblTittle;
    // End of variables declaration//GEN-END:variables

}
